services:
  messenger-db:
    image: postgres:17-alpine
    ports:
      - "10000:5432"
    environment:
      - "POSTGRES_DB=dotnet_messenger_db"
      - "POSTGRES_USER=dotnet_messenger"
      - "POSTGRES_PASSWORD=dotnet_messenger"
    volumes:
      - ./messenger-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dotnet_messenger -d dotnet_messenger_db"]
      interval: 1s
      timeout: 5s
      retries: 10
      
  # https://docs.datalust.co/docs/getting-started-with-docker
  seq:
    image: datalust/seq
    ports:
      - "5341:80"
    environment:
      - "ACCEPT_EULA=Y"
      # commands:
      #   - for windows powershell: $PH = '<password>' | docker run --rm -i datalust/seq config hash        
      #   - for linux: PH=$(echo '<password>' | docker run --rm -i datalust/seq config hash)
      # to set an initial password for the admin user account; 
      # replace <password> with your desired password; 
      # the first line above stores a cryptographic hash of the password into the environment variable $PH (bash syntax);
      # hashed "admin" string: QEGOdfyMit68wWx8hzr0VT3JmNt/LT9HlERYsguNJzGLtvQIyizvecNaidRMWAblwnFImfoFx/O1nR6aONeEgsKMxqDd+oxSZgsRRfHKH7Gg
      - "SEQ_FIRSTRUN_ADMINPASSWORDHASH=QEGOdfyMit68wWx8hzr0VT3JmNt/LT9HlERYsguNJzGLtvQIyizvecNaidRMWAblwnFImfoFx/O1nR6aONeEgsKMxqDd+oxSZgsRRfHKH7Gg"
        
  observe:
    image: grafana/otel-lgtm
    ports:
      - "4318:4318"
      - "4317:4317"
      - "3000:3000"