services:
  messenger-db:
    image: postgres:17-alpine
    ports:
      - "10000:5432"
    environment:
      - "POSTGRES_DB=dotnet_messenger_db"
      - "POSTGRES_USER=dotnet_messenger"
      - "POSTGRES_PASSWORD=dotnet_messenger"
    volumes:
      - ./messenger-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dotnet_messenger -d dotnet_messenger_db"]
      interval: 1s
      timeout: 5s
      retries: 10